### ISSUE TITLE
TypeError: sanitize_filename() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by chrisloughnane** [nonsleepr/edu_10gen_dl#10]
I just tried to grab my finished 10gen M101J course and got this error.

Traceback (most recent call last):
  File "edx_dl.py", line 204, in <module>
    edxb.download()
  File "edx_dl.py", line 141, in download
    sanitize_filename(course_name, replace_space_with_underscore),
TypeError: sanitize_filename() takes exactly 1 argument (2 given)

**Comment by fhenri** [comment]
Hi,

had the same issue and update the script from issue #9 so now it is working fine (on mac osx)
