### ISSUE TITLE
Error on start downloading

### ISSUE THREAD

**Issue by mariuszs** [nonsleepr/edu_10gen_dl#3]
<pre>$ python2.7 edu_10gen.py
[01] CS169.1x Software as a Service
    [01] Overview

...
    [07] Week 6

-----------------------
Start downloading
-----------------------

Processing CS169_1x_Software_as_a_Service/Overview/01.01.*...
Traceback (most recent call last):
  File "edu_10gen.py", line 175, in <module>
    tgb.download()
  File "edu_10gen.py", line 145, in download
    par_soup = BeautifulSoup(par.read())
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 172, in __init__
    self._feed()
  File "/usr/lib/python2.7/site-packages/bs4/__init__.py", line 185, in _feed
    self.builder.feed(self.markup)
  File "/usr/lib/python2.7/site-packages/bs4/builder/_lxml.py", line 195, in feed
    self.parser.close()
  File "parser.pxi", line 1171, in lxml.etree._FeedParser.close (src/lxml/lxml.etree.c:84800)
  File "parsertarget.pxi", line 126, in lxml.etree._TargetParserContext._handleParseResult (src/lxml/lxml.etree.c:93961)
  File "lxml.etree.pyx", line 282, in lxml.etree._ExceptionContext._raise_if_stored (src/lxml/lxml.etree.c:8216)
  File "saxparser.pxi", line 273, in lxml.etree._handleSaxCData (src/lxml/lxml.etree.c:90291)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 527: invalid start byte</pre>

**Comment by nonsleepr** [comment]
Not sure if this helps, but could you check with the last commit?
